### ISSUE TITLE
Access Control Origin header error

### ISSUE THREAD

**Issue by BryMC** [clrksanford/date-night#7]
We're experiencing an issue with our ability to access the API. At first we thought it was in issue with CORS, but we installed it and that didn't work. We've read online that it is an issue with headers, so we tried writing that into the ajax call, but no such luck. (We realize now that CORS isn't needed on the frontend...) but that's primarily what we're finding online. Any suggestions? 

<img width="1259" alt="screen shot 2016-10-24 at 10 38 07 am" src="https://cloud.githubusercontent.com/assets/19334869/19652327/fe74b3d6-99d5-11e6-88fc-878be7f7f106.png">

**Comment by rldaggie** [comment]
@BryMC the API you're accessing doesn't allow ajax from a separate domain. Couple of workarounds:
1. Hit an internal endpoint in your Node app that then hits the API
2. Use `jsonp` in your ajax requests.

**Comment by BryMC** [comment]
Got it, thank you!
